---
- name: Install docker-compose for python
  pip:
    name:
    - requests==2.31.0
    - docker<7.0
    - docker-compose

- name: Git checkout
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: Docker compose up
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes